### ISSUE TITLE
All logins fail since 11.1.2019

### ISSUE THREAD

**Issue by gruijter** [simplyGits/MagisterJS#106]
I get multiple reports from users that the login fails. It also fails for the three students I am testing with myself. Does anyone know what is going on?

**Comment by lieuwex** [comment]
Yes, yesterday I've received #105. But it hasn't been pushed yet (my bad), I will do that in an hour or so. That should fix it.

**Comment by lieuwex** [comment]
I've published 2.0.0-alpha.5, hopefully that fixes your problems.

**Comment by gruijter** [comment]
Good job! Will test this afternoon and let you know.

**Comment by gruijter** [comment]
Yep, seems to be working again. Thx!
