### ISSUE TITLE
Request: Push isParent update to npm

### ISSUE THREAD

**Issue by 7kasper** [simplyGits/MagisterJS#123]
😄 
I kinda need the isparent function and while importing from github works a bit, it is sometimes a pain in the ass.
Can we go to alpha 10?

**Comment by Sj3rd** [comment]
Yes please! 😄

**Comment by Argetan** [comment]
What you can do till then is the following in `package.json`:
```
"dependencies": {
    ...
    "magister.js": "https://github.com/simplyGits/MagisterJS.git#d82ee0c",
    ...
  },
```

**Comment by 7kasper** [comment]
![image](https://user-images.githubusercontent.com/6474340/53631494-f04a7480-3c12-11e9-9f91-ee86c463b36a.png)
:(

**Comment by lieuwex** [comment]
published!
