### ISSUE TITLE
Grades not fetching.

### ISSUE THREAD

**Issue by iranathan** [simplyGits/MagisterJS#126]
Hello everyone,

Am I doing something wrong or does it not work like that

code:
 ```javascript
async function fetchGrades(err, magisterlogin) {

  magisterlogin.courses()
  .then(res => res.find(c => c.current))
        .then(c => c.grades({
          fillGrades: false,
          latest: true,
        }))
  .then(r => {
    for (i = 0; i < r.length; i++) {
      r[i].path = CACHE_PATH + "grade_" + r[i].id + ".json";
      if (fs.existsSync(r[i].path)) {
        tools.log("notice", r[i].id + " Grade is in cache.");

      } else {
        fs.writeFileSync(r[i].path, JSON.stringify(r[i]));
        tools.log("notice", r[i].id + " New Grade is in cache.");
        tools.sendPush(CONFIG.pushover, {
        title: "Grade",
        message: `you got a ${r[i].grade} for ${r[i].class.description}`

        })
        console.log(r[i].class.description)
      }
    }
  });

}
```
I want this to get the latest grades if there is any an send me a notification with pushover but when I get a new grade it doesn't do anything?

Thanks, Ira.

**Comment by lieuwex** [comment]
Can you check what code it does execute? Glancing over your code it seems to be correct, and knowing till how far the code executes probably is useful to know.

**Comment by Sj3rd** [comment]
Debug. Do you get the grades array? Do you get any errors? Put some debug .logs in your code to test please. Other wise there may be a problem with the r[I].xxxx since some grades don't have all the properties like teachers[0] etc.

**Comment by Argetan** [comment]
Also, keep in mind that if you tested your code and it didn’t work and then you ran it again that it might be in cache (and thus it won’t send a notification). Make sure that the grade is not cached when running your tests.

**Comment by iranathan** [comment]
Hello, thank you all for responding.

So the code 100% runs all the way through
I have tried:

Changing the latest option to false shows all my grades but not new ones.
I'm also not sure what the fillGrades option does. (It was in the test file here https://github.com/simplyGits/MagisterJS/blob/master/test/test.js)

Right now it just returns an empty array.

It's also not to do with the cache because I have been getting new grades when the code was running.

Thanks.

**Comment by Argetan** [comment]
Setting the `fillGrades` option runs the following function on all fetched grades:

https://github.com/simplyGits/MagisterJS/blob/0bbd17b40ec67d5c3955ea957588443fc3e9fbff/src/grade.js#L122-L144

You should be able to set it to false (as it doesn't provide anything required by your script). I would set the `latest` option to false, I believe it had a couple issues. It will then fetch all grades you ever got for that subject (at least it should).

Which function returns an empty array exactly? And could it be that your `tools.sendPush()` function is broken?

**Comment by iranathan** [comment]
@Argetan Thanks for replying and sorry for the kind of late reply, 

The sendPush() does work I have tested it 

The function that returns an empty array is the function that gets my grades.
I have tried it without the latest open on
I get grades but not new ones.

Also.

From what date does the latest option fetch?

Thanks, Ira.

**Comment by iranathan** [comment]
Just in case I will check if it actually is getting grades but `tools.sendPush()` doesn't work.

**Comment by Argetan** [comment]
```js
async function fetchGrades(err, magisterlogin) {

 magisterlogin.courses()
 .then(res => res.find(c => c.current))
       .then(c => c.grades({
         fillGrades: false,
         latest: false,
       }))
 .then(r => {
   for (i = 0; i < r.length; i++) {
     r[i].path = CACHE_PATH + "grade_" + r[i].id + ".json";
     if (fs.existsSync(r[i].path)) {
       tools.log("notice", r[i].id + " Grade is in cache.");

     } else {
       fs.writeFileSync(r[i].path, JSON.stringify(r[i]));
       tools.log("notice", r[i].id + " New Grade is in cache.");
       tools.sendPush(CONFIG.pushover, {
       title: "Grade",
       message: `you got a ${r[i].grade} for ${r[i].class.description}`

       })
       console.log(r[i].class.description)
     }
   }
 });

}
```

Running it like this works for me, you might want to check if there is something wrong with the `course` for you. Just in case Magister puts your grades in a different course than the current one.

**Comment by iranathan** [comment]
Update.

Grades coming in now but about 1-2 days late.

Is this something to do with `course`?

**Comment by Argetan** [comment]
It might be, I know that I'm in 2 different courses at the same time (because my school is kinda weird). You could loop over all courses and then check if `course.current` is `true` because I think that the `#find()` method just returns the first element that has `course.current === true`. And then it might just be a coincidence that your grade is only noticed after 1/2 days (since it kind of returns a random course).

**Comment by lieuwex** [comment]
How does something like the following work?

```javascript
async function fetchGrades(magisterlogin) {
	const courses = await magisterlogin.courses();

	for (const course of courses.filter(c => c.current)) {
		const grades = await course.grades({
			fillGrades: false,
			latest: true,
		});

		for (const grade of grades) {
			const path = CACHE_PATH + "grade_" + grade.id + ".json";

			if (fs.existsSync(path)) {
				tools.log("notice", grade.id + " Grade is in cache.");
				continue;
			}

			fs.writeFileSync(path, JSON.stringify(grade));
			tools.log("notice", grade.id + " New Grade is in cache.");
			tools.sendPush(CONFIG.pushover, {
				title: "Grade",
				message: `you got a ${grade.grade} for ${grade.class.description}`,
			});
			console.log(grade.class.description);
		}
	}
}
```

**Comment by iranathan** [comment]
Hello,
I fixed the problem by looping through both courses and getting the grades.
My class was getting split into 2 classes at this time and that's why I think this happened.

Is it a problem if I don't use `c.current`? because it works fine without it.

Massive thanks to everyone that helped.
Ira,

**Comment by Argetan** [comment]
It should not be a problem. It might make your code just a bit more efficient, since it then doesn’t check your grades from previous years but it shouldn’t be an issue. You could try running the script with `c.current` checks to see if it still works, if so it will execute faster (but I don’t think you’ll really notice any difference).
