### ISSUE TITLE
Mistake in homepage example

### ISSUE THREAD

**Issue by IsaiahvH** [simplyGits/MagisterJS#13]
Hey,

I was planning on filing a whole problem, but I'll save you the pain. I spent quite some time on figuring out and examining why the first example of your homepage does not work.
Guys, I think you might want to change `teachers[0]` to `teachers()[0]`, :]

**Comment by IsaiahvH** [comment]
My previous problem:


Hello,

I got this code from your project homepage,
```javascript
new Magister("Dalton Den Haag", "<username>", "<password>").ready(function (error) {
    if (error) {console.log("ouch. ", error); return false;}
    this.appointments( new Date(), function (error, result) {
console.log(result[0].teachers[0].fullName());
});
});
```
and I can understand what's happening, but it doesn't work.
I actually find the `result` value difficult to understand.
It consists of for arrays inside, so and upon further inspecting I indeed need only the first array, thus `result[0]`. But then; it seems all the actual values are stored inside with an underscore before their name, such as "_classes", "_description" and "_teachers", and the version without the underscore is some sort of handler. Am I correct in understanding this :]? Because I feel like I need to understand the format of the `result` value to be able to use it correctly. As I understand it, the actual variable name ("classes", "description" and "teachers" - without underscore) are a function to check whether the requested value is present/not null - it seems to validate. Then, if found valid, it returns the value, as can be seen at the end of the function of this handler, [...] `return _.isFunction(c)?c(this[a],!1):this[a]`.
Upon even further examining, in the `Closure` of the `<function scope>` of this handler (all via Chrome Developer Tools), there is indeed a variable `a` which points to the actual value, `_teachers`, as shown in the picture below.
![teachers](https://cloud.githubusercontent.com/assets/1858814/6233795/d5ce505c-b6d5-11e4-8ba4-e790da3a569c.png)
And then the value `_teachers` has several arrays, but we only need the first - thus `teachers[0]`, and the result of this is similar again, with `_fullname` as value and `fullname()` as handler to access this variable.

My problem is, `result[0].teachers[0]` results `undefined`. No error, and the value (`_teachers`, `a`, whatever you wish to call it) is most certainly present. That's my problem.
An additional question I have, is why are square brackets used for `teachers[0]` and just paratheses for `fullName()`? I can understand


*realization I could try adding ()*

**Comment by IsaiahvH** [comment]
Oh, and could possibly `window.onbeforeunload` be added to your TryOut when the text is changed once, just like JSFiddle? This is just a personal request, but I have pressed backspace quite some time instead of enter, losing my work (which wasn't much, but still).

**Comment by lieuwex** [comment]
Hey Isaiah,

You're correct, the values are stored in `_{varname}` and `{varname}` is a getter/setter function which get's the result and sets, (if allowed) it also does some parsing if needed. See https://github.com/simplyGits/MagisterJS/blob/master/src/private/Helpers.coffee#L65

You could use all variable names with underscore before them but this might return unexpected values or allows you to set values that are ignored. Sometimes the setter also does a request, (eg https://github.com/simplyGits/MagisterJS/blob/master/src/Appointment.coffee#L116).

`teachers[0]` should indeed be `teachers()[0]`, my fault, (again :P).

I'm going to fix the error and look into adding a close warning, although I'm pretty bussy right now.

`Keeping this open until both are commited.`

**Comment by IsaiahvH** [comment]
Okay, I understand! Thanks for your quick reply!
