### ISSUE TITLE
Test fails at creating appointments

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#132]
For example: https://travis-ci.org/simplyGits/MagisterJS/builds/528474052

Can anybody with a working account figure this out?

**Comment by Argetan** [comment]
https://github.com/simplyGits/MagisterJS/blob/eab7d468d0b93e08f522200027aa659045f815b0/test/test.js#L243-L253

I took a quick look at it and it appears to me that `r` is empty, which leads me to the following conclusions a) my schedule is great b) the appointment was never created.

I'll see if I'm able to figure out exactly where it goes wrong.

**Comment by lieuwex** [comment]
I envy your free time ;)

**Comment by Argetan** [comment]
Right, so I'm 100% sure now that the appointment is not being created.. no idea why though. Is there a way to see when this test failed for the first time?

**Comment by Argetan** [comment]
Found it, appears that it first occurred in [build #352](https://travis-ci.org/simplyGits/MagisterJS/builds/503316090). Seems that #124 and #125 might be related.

**Comment by lieuwex** [comment]
I agree the bug is important, but the critical tag is more meant for stuff that (may) completely break MagisterJS. I've added a description for clarity.

This issue itself _is_ confusing, I am curious to what the solution is.

**Comment by lieuwex** [comment]
[It seems to be still broken](https://travis-ci.org/simplyGits/MagisterJS/builds/528521141), sadly I can't test it myself

**Comment by Argetan** [comment]
It must somehow be a user-specific issue in a way then because mine is still working (and I checked again). Could it be that there is something wrong with the account used on Travis? Par example that it doesn't have permission to delete appointments or such?

**Comment by Argetan** [comment]
I just ran the test again (in reference to #132) and I'm getting the error as well. I think however that it is the test that is faulty, not the code itself. I'll try and see if I can figure out how to fix it.

**Comment by Argetan** [comment]
Right, sorry I took so long, I looked into it today and it seems that the appointment is not being created. Looking at the `HTTP_POST` response:
```
Response {
  size: 0,
  timeout: 30000,
  [Symbol(Body internals)]:
   { body:
      PassThrough {
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     disturbed: false,
     error: null },
  [Symbol(Response internals)]:
   { url: 'https://zwin.magister.net/api/personen/3182/afspraken',
     status: 400,
     statusText: 'Bad Request',
     headers: Headers { [Symbol(map)]: [Object] },
     counter: 0 } }
```

I'll see if I can figure out what's going on here.
