### ISSUE TITLE
AuthError: invalid username

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [simplyGits/MagisterJS#139]
I don't know if this is a temporary error at Magisters side, but it seems like their site is working normally and their status site isn't reporting any outages.

When attempting to login since sometime today MagisterJS returns an AuthError. The underlying problem is that Magister returns a 400 (bad request) error on the https://accounts.magister.net/challenge/username request.

I have seen this happen a couple of times  before, but on the https://accounts.magister.net/challenge/password request. And that would fix itself after 10 minutes. I hope somebody with more knowledge of the API's inner workings can look into this soon.

Edit: After 5 hours I still can't login using the library

**Comment by Sj3rd** [comment]
No problems over here. I do know that the username & password validation is done by a server from the school itself, and that if that one is offline you'll get that error. Maybe they're updating or moving the server.

This is not an issue related to this repository.

**Comment by LevitatingBusinessMan** [comment]
I am indeed able to login from an incognitor browser. Everything seems fine when accessing from the normal website. But I think I know what's happening, does magisterJS rely on the school url or also the school id when using a specific school to login with?

**Comment by LevitatingBusinessMan** [comment]
Nope, I checked and it's still up to date.

**Comment by robbertkl** [comment]
Having the same issue (400 bad request on /challenge/username) since 1 or 2 days.

**Comment by jvdoorn** [comment]
I think there is an issue with the headers. It appears that Magister has `x-client-id` in their request header, but as far as I can tell we don't.

**Comment by robbertkl** [comment]
I've added this header to the `/challenge/username` call, but unfortunately I'm still getting the same (400) result. Must be something else. I'll play around with some changes.

**Comment by LevitatingBusinessMan** [comment]
Great, I can look into it tomorrow if it's not fixed by then yet.

**Comment by robbertkl** [comment]
After adding better error handling to the response (#140) I found out the authCode was denied. After using the one from my school's website, it works again, but I guess this is where the accreditation (https://github.com/simplyGits/MagisterJS#accreditation) comes in? @lieuwex

**Comment by robbertkl** [comment]
Now, after improving the error handling a bit more (see 2nd commit in #140), I'm getting a 403 error with `Invalid API key`. Not during the actual login, but when doing `retrieveAccount()` directly after. Is this because I'm "borrowing" the website authCode instead of requesting one from Iddink Digital?

So, summarizing:

* When using the authCode from `@magisterjs/authcode` I'm getting `AuthCodeValidation` error.
* When using the authCode from my school's Magister site, I'm getting `Invalid API key`.

**Comment by robbertkl** [comment]
Scratch that, my bad: I had removed a bit too much stuff when debugging

It just works with the new authCode (`ebe61b7d`). I've also just found out about `@magisterjs/dynamic-authcode`, so I'll be using that from now on.

**Comment by robbertkl** [comment]
By the way, @lieuwex (or perhaps his automated twin) already updated `@magisterjs/authcode` 2 days ago with the new authCode, so simply updating this package should suffice. Issue closed?

**Comment by Sj3rd** [comment]
Just so you guys know: Magister has a new oauth style login available used in the official apps. Only need to authenticate 1 time and you'll be able to refresh your tokens after :)

You can get the login http shit by reverse engineering the app (proxy or any other creative way to check your phone or emulator's network requests) 

Cheers :)

**Comment by LevitatingBusinessMan** [comment]
As @robbertkl pointed out, this issue has already been fixed.
