### ISSUE TITLE
Change the getsetter style to normal properties.

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#15]
`_convertRaw` and functions such as `Mail.send` are way better candidates for converting unconverted properties and will lead to faster and cleaner code.

**Comment by lieuwex** [comment]
@simplyGits/simplycoders thoughts? concerns?

**Comment by tomsmeding** [comment]
You might be able to use the real `Object.create` getters/setters. Won't make the code faster though, just make the API cleaner and more magical. Because that's just what we need. Making the code faster is great though — if you know how to do that, do that.

**Comment by lieuwex** [comment]
I thought about native getter and setters a bit, but they're not really correctly supported everywhere. The best I can think of is not using getter and setters but that will create some limits at places. This is the most magical I can make it I guess.

But the performance and cleanness of the end-user's code is uglier. *sigh* I don't know

**Comment by tomsmeding** [comment]
I'd say make them normal properties and handle conversion separately. That makes for a little more code bloat everywhere, but the result might be slightly faster, and stuff's cleaner, in a way. That way, you can cache a conversion when you'd be doing it multiple times with the setters or something. Dunno. If you'd do the conversion everywhere anyway, you could just as well keep the setters and roll with it.

**Comment by lieuwex** [comment]
Well, I'm mostly worried about things like https://github.com/simplyGits/MagisterJS/blob/master/src/Message.coffee#L57. That whole line is pure magic with getter/setter's, man.

**Comment by tomsmeding** [comment]
Yeah but help. You shouldn't use a setter like that. Setting a normal property shouldn't do *networking*, at the very least. Make it a read-only property (i.e. a function) and make a separate `move` function that updates that internal property, besides also doing the communication to the Magister server.

**Comment by lieuwex** [comment]
Hmm good point. 2.0 will have all getter/setters removed, or if needed, replaced with native getter/setters.

**Comment by lieuwex** [comment]
Done on the v2 branch

**Comment by tomsmeding** [comment]
🎉
