### ISSUE TITLE
Invalid username error

### ISSUE THREAD

**Issue by pascal541** [simplyGits/MagisterJS#151]
Since a few weeks, I am getting the following error when trying to login to Magister:

`something went wrong: AuthError: Invalid username
    at Magister.login (...\node_modules\magister.js\lib\magister.js:617:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'AuthError'
}`

**Comment by stingalleman** [comment]
Did you fix this issue?

**Comment by pascal541** [comment]
Yes, #150 fixed it for me.

**Comment by stingalleman** [comment]
Thanks, I'll take a look at it.
