### ISSUE TITLE
Meteor support

### ISSUE THREAD

**Issue by Tim-W** [simplyGits/MagisterJS#16]
Hey, what happened to your meteor package?

```
While adding package simply:magisterjs:
error: no such package
```

**Comment by lieuwex** [comment]
Hey,
Nothing really, there were issues with implementing it so it was never there... ^^'
Sorry, I will look into it again, if you need it now, a good solution is to move the `src/` folder to your meteor `lib/` folder and remove:
- `private/_deps.coffee`
- `http/http.js`

You also need the `coffeescript` package.

Our HTTP method:
```CoffeeScript
request = Meteor.npmRequire "request"
Future = Npm.require "fibers/future"

Meteor.methods
	###*
	# Do a HTTP request.
	# @method http
	# @param method {String} The HTTP method to use.
	# @param url {String} The URL to send the HTTP request to.
	# @param options {Object} A request settings object.
	# @return {Object} { content: String, headers: Object }
	###
	http: (method, url, options = {}) ->
		@unblock()
		fut = new Future()

		opt = _.extend options, {
			method
			url
			headers
			jar: no
			body: options.data ? options.content
			json: options.data?
		}

		request opt, (error, response, content) ->
			if error? then fut.throw error
			else fut.return { content, headers: response.headers }

		fut.wait()
```

I know this is highly impractical, sorry for the mess.

_Keeping this issue open until I finally added a working Meteor package_

**Comment by lieuwex** [comment]
Sorry for the long wait. But it's here, fully working.
Example: https://github.com/lieuwex/magisterjs-example
