### ISSUE TITLE
Call callback Magister.getPersons async if persons were cached

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#24]
cc @tomsmeding

**Comment by tomsmeding** [comment]
Well you kn

**Comment by tomsmeding** [comment]
God forsaken touchscreens that let you press the wrong button.
What I WANTED TO SAY: Well youknow how to do this: _.defer, process.nextTick,, setTimeout(...,0) :)

**Comment by lieuwex** [comment]
The only problem I have is that I have no fucking idea how to test if the cached result is being used.

**Comment by tomsmeding** [comment]
Well you can test for time taken with `console.hrtime()`; that number should be *really* low when using the cached version. Not really a reliable test though.
You can count ticks by also registering a function in the test with something like

    var ticks=0,shouldContinueTicking=true;
    var f=function(){
        ticks++;
        if(shouldContinueTicking)process.nextTick(f);
    };
    process.nextTick(f);

Then you can check the `ticks` variable in the `getPersons` to check whether it was a cached version, and set `shouldContinueTicking=false`. Haven't tested anything, so check for yourself if this works. The exact number of `ticks` you get might or might not be dependent on the Node version.

**Comment by lieuwex** [comment]
Haha I used another, simplier solution. :P

**Comment by tomsmeding** [comment]
Guess that works; doesn't look like an ideal solution either, but got to do something.

**Comment by lieuwex** [comment]
Why not? What are your concerns?

**Comment by tomsmeding** [comment]
Okay, have to admit that most people won't notice the boolean being returned. You've got to document it, though, because you rely on it in the test.

**Comment by lieuwex** [comment]
@tomsmeding it is already, https://github.com/simplyGits/MagisterJS/commit/2d5e01133767ad539c5a8860f76978928931275d#diff-dc8ca739394421dde815fc3ef96e0396R301

**Comment by lieuwex** [comment]
oh damn, that is wrong :P `param` -> `return`

**Comment by tomsmeding** [comment]
👍

**Comment by lieuwex** [comment]
59a31155f7f11ad97dceaff91b388d2ff8709f11
