### ISSUE TITLE
High ECONNRESET error rate

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#25]
Magister is throwing a hell of a lot errors at my face, are they ratelimiting us or is it just _another_ slight hiccup at their side?

**Comment by tomsmeding** [comment]
Econnreset means the socket was forcibly closed on the other end, so ratelimit is quite possible. If it is a bug, then the official client should be affected too — iff their client doesn't just retry the request, which I suppose helps.

**Comment by lieuwex** [comment]
That's the weird thing, if I use the webclient everything is fine. If I run the magister.js tests and come back to the webclient, the webclient will _sometimes_ fail for the first couple repsonses.

It could be an intended ratelimit or an unintened one ( their servers fucking up for example )

**Comment by lieuwex** [comment]
Update: their client is broken af as well, had to click 3 times on a message to get it to open
