### ISSUE TITLE
Retry login process parts after error

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#26]
Like a configurable (eg default 5 times) retry option which for example retries fetching the messagesFolders if that fails.

**Comment by nloomans** [comment]
Does failing include wrong password? Because 5 times wrong is enough to get you blocked.

**Comment by lieuwex** [comment]
@nloomans Thanks for the headsup! Retries are used when we get an unexpected result back from Magister, so stuff like a blocked account or wrong credentials will not trigger a retry.

**Comment by lieuwex** [comment]
The only thing we're still retrieving during login is (expect from just sending the POST request) from `/api/account`, I doubt it's still useful to retry that when it fails. @simplyGits/simplycoders?

**Comment by lieuwex** [comment]
After a short discussion with @tomsmeding we agreed that just failing is the best strategy now.
