### ISSUE TITLE
Use null for errors to callbacks everywhere

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#27]
We currently mix `null` and `undefined` as the error paramter on callbacks, this forces users to check `!= null`, if we use `null` everywhere people can check with `!== null`.

**Comment by tomsmeding** [comment]
NULL NULL NULL

**Comment by lieuwex** [comment]
@tomsmeding it doesn't matter for me really, is `null` more common, if so we can do that

**Comment by tomsmeding** [comment]
Well, for me at least:
- `undefined` means there is nothing, nor could there ever have been anything
- `null` means there is nothing, but there could, potentially, have been something
So I always use `null` for non-existant errors and such.

**Comment by lieuwex** [comment]
@tomsmeding I just searched around and https://docs.nodejitsu.com/articles/errors/what-are-the-error-conventions tells the same thing. `null` it will be.

**Comment by tomsmeding** [comment]
\o/ my own conventions match with common conventions

**Comment by lieuwex** [comment]
That was easy

**Comment by tomsmeding** [comment]
lol
