### ISSUE TITLE
Incorrect error notification upon invalid login

### ISSUE THREAD

**Issue by IsaiahvH** [simplyGits/MagisterJS#29]
Hello,

When I provide an incorrect login on your TryOut, instead of neatly stating the login was invalid or something like that, `magister-browser-noHttp.min.js:3` reports `Uncaught TypeError: Cannot read property '0' of undefined`, which completely breaks the `if (error)`.
Can this be fixed?

Kind regards,

Isaiah van Hunen

**Comment by lieuwex** [comment]
Hey Isaiah!

Fixed, sorry for the inconvenience.

The bug was only on the tryout, since I forgot to add http statuscode handling there.
We might add an wrapper around magister-http so that all the http implementations have http statuscode handling automatically added.

Thanks for your report!
