### ISSUE TITLE
magister api weer aangepast (Cannot read property 'map' of null)

### ISSUE THREAD

**Issue by bwired-nl** [simplyGits/MagisterJS#34]
de laatste dagen komt deze fout weer continue, dus onderstaande loopt niet
Lijkt dat weer wat is aagepast?

          result.map(function (g) {
TypeError: Cannot read property 'map' of null

```
function getData() {	
	new Magister.Magister({
		school: {
			url: 'https://dspierson.magister.net'
		},
		username: 'p.username',
		password: '<<<iets>>>'
	}).ready(function () {
		this.children(function (e, r) {
			r.forEach(function (m) {
				//console.log('courses +++++++++++++++++++++++ :'+ util.inspect(m));
				m.courses(function (error, result) {
					result[0].grades(true, true, true, function (error, result) {
						result.map(function (g) {
							punt.naam = m.profileInfo().firstName();
							punt.punt = g.grade();
```

**Comment by tomsmeding** [comment]
Ik heb de vrijheid genomen om je post iets aan te passen: wat styling, en het verwijderen van het wachtwoord uit de code.
Lieuwex is op dit moment niet aanwezig, en ik weet veel te weinig van de hele library om je hierbij van dienst te zijn. Als hij terug is, zal hij ernaar kijken. :)

Dat de Magister API is aangepast, is overigens zeer goed denkbaar. Het is niet bepaald een stabiele of goed georganiseerde API...

**Comment by bwired-nl** [comment]
thanks:-)

**Comment by bwired-nl** [comment]
Api werkt weer for now :-)

**Comment by lieuwex** [comment]
Je hebt in de callback van `result[0].grades` niet gecontroleerd of `error` een waarde heeft, ik verwacht dat in dit geval Magister een foutmelding terug gaf, waardoor `result` `null` is.

**Comment by bwired-nl** [comment]
ja klopt, ik heb het aangepast, maar magister lag er mbt de api weer eens 2 dagen uit :-(
dank!
