### ISSUE TITLE
Add ability to add and remove custom appointments

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#35]
We should also show if an appointment is customly made (have to research how this is possible to detect, guess the `Type` field)

**Comment by tomsmeding** [comment]
And let the user choose the exact time I suppose? Instead of 5-minute multiples or what's it what they do? ;-)

**Comment by lieuwex** [comment]
30 minute intervals, ___30 MINUTE___

**Comment by tomsmeding** [comment]
D:
