### ISSUE TITLE
'OngeldigeSessieStatus'

### ISSUE THREAD

**Issue by w00tc0d3** [simplyGits/MagisterJS#36]
Hello,

Using this code:
```JavaScript
var Magister = require("magister.js");

new Magister.Magister({
        school: '',
        username: '',
        password: ''
}).ready(function (error) {
    if (error) console.log("ouch. ", error);
    else alert("Hey, " + this.profileInfo().firstName() + "!");
});
```

Gives the following error: ouch.  ```{ fouttype: 'OngeldigeSessieStatus',
  omschrijving: null,
  toString: [Function] }```

What could potentially be the problem? My school is on version 6.0.26.

Thank you.

**Comment by tkon99** [comment]
Hi,

We are aware of the issue and are currently working to fix it.
I'd like to remind you of the fact that Magister.js is distributed under GPLv3 which means that you have to:
- Make all your projects open source under the GPLv3 license that use Magister.js
- Provide proper credit in all your projects to the Magister.js library

If you definitely don't want to make your project open source you can always reach out to me and I'll be more than delighted to discuss this with you. It's just that we like to know what you are using it for so we could even showcase it.

Thanks in advance

Thomas Konings, simply

**Comment by lieuwex** [comment]
Hey,

Thanks for your bug report!
I was aware of the problem but only got time to fix it this evening, sorry for the inconvenience.
I don't exactly know the reason the login process suddenly broke, but it has to do with some change at Magister's side.

Please update your version of 'magister.js' by using `npm install --save magister.js` once again in your project folder.

Have fun building!
Lieuwe Rooijakkers
simply

**Comment by bwired-nl** [comment]
thanks for the good service, working again!
