### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by JuulvanBracht** [simplyGits/MagisterJS#37]
Hallo,
Ik neem aan dat je nederlands bent.
Ik wil graag een Field waar je je leerling nummer kan invullen en daarna op go drukt dat het je rooster ophaalt. Maar het lukt mij maar niet, Ik weet niet waar ik moet beginnen. 

Ik wil eigenlijk een tabel van
Deze dag:
+------------------+------------------+
| Hour               | Class  Room  | 
+------------------+------------------+

- Juul

**Comment by lieuwex** [comment]
Hey Juul,

Om te beginnen heb je enige kennis of van node.js of van Meteor nodig.
In deze situatie zou ik met [express](http://expressjs.com/) werken, daarvia host je dan een webpagina, gewoon een simpele HTML pagina zou voldoende moeten zijn, met een beetje clientside javascript code die bijvoorbeeld via jQuery AJAX informatie van je express server haalt via een REST endpoint.

De endpoint zou dan alles van inloggen tot data ophalen kunnen regelen, zoiets als:
```
app.get('/rooster/:school/:username/:password', function (req, res) {
	var Magister = require('magister.js').Magister;
	new Magister({
		school: req.params.school,
		username: req.params.username,
		password: req.params.password,
	}).ready(function (e) {
		if (e) {
			res.status(500).end('Error while logging in');
			return;
		}

		this.appointments(new Date, function (e, r) {
			if (e) {
				res.status(500).end('Error while fetching appointments');
				return;
			} else {
				res.json(r.map(function (a) {
					return {
						begin: a.begin(),
						end: a.end(),
						description: a.description(),
					}
				}));
			}
		});
	});
})
```

**Comment by lesander** [comment]
Wat heb je al geprobeerd?

**Comment by tkon99** [comment]
Hi Juul,

Volgensmij wil je iets wat niet mogelijk is. Hoe ik het interpreteer wil je dat je alleen je leerlingnummer hoeft in te vullen. Dat kan niet omdat je altijd moet inloggen met Magister. Tenzij je school een gepro-osi rooster gebruikt. Zou je kunnen verduidelijken wat je wilt bereiken?

Alvast bedankt!

**Comment by JuulvanBracht** [comment]
Mijn school gebruikt idd gepro-osi roosters.
Met Express kan ik niet echt overweg. Dit wordt te moeilijk.

Is er een soort PHP api voor geopro roosters?

Btw. Ik ben 14 dus ik kan niet al teveel qua Jquery, Php snap ik veeeel beter.

**Comment by tkon99** [comment]
Hi Juul,

Wat leuk dat je PHP kan, zo ben ik ook begonnen :smile: 
Blijkbaar is vandaag je geluksdag want ik heb een library gemaakt in PHP die precies dat doet!
https://github.com/tkon99/API-gepro-osi

Mocht je vragen hebben dan kun je daar een issue aanmaken.
Veel plezier!

**Comment by JuulvanBracht** [comment]
Tof! Thanks
