### ISSUE TITLE
Add support for changing password

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#40]

**Comment by lesander** [comment]
Changing a Magister password seems to consist of the following steps:

1. **GET** `/api/sessions/current`
    Check the returned `isVerified` value. If set to `true` we continue to step three, otherwise we have to validate that we know the current password first.

2. **POST** `/api/sessies/huidige/valideer`
    Contains JSON body payload with current password:
    ```json
    { "wachtwoord": "xxx" }
    ```
    After a `200 OK`, the response should contain an JSON object with `isVerified` set to `true`.
    The response also contains `links.account.href` with a typical value of `/api/accounts/12345`

3. **PUT** `/api/accounts/12345/wachtwoord`
    JSON body payload:
    ```json
    { "wachtwoord": "xxx", "wachtwoordControle": "xxx" }
    ```
    The response should have a `204 No Content` header set if the change was successful.

Do you want me to create a PR in `v2` @lieuwex ?

**Comment by lieuwex** [comment]
Thanks, that sounds not too bad.

> Do you want me to create a PR in v2 @lieuwex ?

That would be amazing, yeah! I guess `ProfileSettings` would be a good place for password shit. Tell me if you have any question :)

**Comment by lesander** [comment]
@lieuwex Before continuing, I'd like to make sure my feature branch will be up-to-date with branch v2. However, I can see that the API key hotfix has not been committed to v2 yet, is that correct?

**Comment by lieuwex** [comment]
Good point! I have to commit those changes yet 😳, it's comming.

**Comment by lieuwex** [comment]
Hey @lesander, sorry for the incredible long wait, I had a busy week and weekend :P
I committed and pushed the changes to the v2 branch.

**Comment by lesander** [comment]
No problem @lieuwex, I'll get started on my PR 👍
