### ISSUE TITLE
OnvoldoendePrivileges

### ISSUE THREAD

**Issue by basvdwollenberg** [simplyGits/MagisterJS#48]
I couldn't find anything about this, so I guess I'll just open an issue then.
No idea why, but every time I try to log-in I get `fouttype: "OnvoldoendePrivileges"` back, something wrong with the API or is it just for me for some reason (or am I just stupid)?
![](http://i.imgur.com/jmRuvyD.png)

**Comment by tkon99** [comment]
I believe this is an issue on Magister's end.
Can you confirm that you're able to login through Magister's web client?
If so, it's most likely a problem with your own code. (Feel free to post it here and we'll take a look).

**Comment by lieuwex** [comment]
@basvdwollenberg It could be what @tkon99 said.

But it probably has to do with the fact that your school doesn't have messages enabled. This is an issue that shouldn't really be one. Fixing it requires changing the API of Magister.js based around messages a lot, though. I'm currently working on Magister.js v2 which doesn't have this problem anymore.

If you want (or need) to use Magister.js right now you can hack around the problem by:

1. catching this error;
2. then ignore it;
3. then call `Magister#_setReady()`;
4. proceed to use the `Magister` object how you normally would.

**Comment by basvdwollenberg** [comment]
I used the default code on http://simplyapps.nl/MagisterJS/tryout/, should've mentioned that first.
I can log in through the web client just fine, so I guess my school doesn't have messages enabled then.
Calling `_setReady()` works, but calling `profileInfo()` or logging `_profileInfo` afterwards both return `undefined`.

**Comment by lieuwex** [comment]
Okay weird, can you fill in your information and run this code in the tryout with your devtools open:

```JavaScript
new Magister.Magister({
	school: '<schoolname>',
	username: '<username>',
	password: '<password>'
}).ready(function (error) {
    if (error != null) {
        console.trace(error);
        this.http.get(this.magisterSchool.url + '/api/account', {}, function (e, r) {
            if (e) console.error(e);
            else console.log(JSON.stringify(JSON.parse(r.content).Groep[0]))
        });
    }
});
```

After that expand the `Error()` log using the arrow next to it and take a screenshot of the full stacktrace. Also please paste the JSON blob 2 log entries under that here. (it shouldn't contain any personal information)

**Comment by basvdwollenberg** [comment]
![2016-07-13_115131](https://cloud.githubusercontent.com/assets/7560938/16799258/2e61d132-48f0-11e6-82b5-ad98fddfef36.png)
```json
{"Naam":"Leerling","Privileges":[{"Naam":"Cijfers","AccessType":["Read"]},{"Naam":"Aanmeldingen","AccessType":["Read"]},{"Naam":"WachtwoordWijzigen","AccessType":["Create","Read","Update","Delete"]},{"Naam":"ProfielEmail","AccessType":["Read"]},{"Naam":"DigitaalLesmateriaal","AccessType":["Read"]},{"Naam":"EloOpdracht","AccessType":["None"]},{"Naam":"Studiewijzers","AccessType":["None"]},{"Naam":"Projecten","AccessType":["None"]},{"Naam":"Bronnen","AccessType":["None"]},{"Naam":"Berichten","AccessType":["None"]},{"Naam":"Profiel","AccessType":["Read","Update"]},{"Naam":"ProfielMobiel","AccessType":["Read","Update"]},{"Naam":"Absenties","AccessType":["Read"]},{"Naam":"Afspraken","AccessType":["Create","Read","Update","Delete"]},{"Naam":"Aftekenen","AccessType":["Read","Update"]},{"Naam":"Contactpersonen","AccessType":["Read"]},{"Naam":"Roosterwijzigingen","AccessType":["Read"]},{"Naam":"Instellingen","AccessType":["Create","Read"]},{"Naam":"Activiteiten","AccessType":["None"]},{"Naam":"MataHuiswerk","AccessType":["Read"]},{"Naam":"MataWidgets","AccessType":["Read"]},{"Naam":"MataBerichtMappen","AccessType":["Read"]},{"Naam":"MataKinderen","AccessType":["Read"]},{"Naam":"MataDigitaalLesmateriaal","AccessType":["Read"]},{"Naam":"MataEloOpdracht","AccessType":["Read"]},{"Naam":"MataBerichten","AccessType":["Create","Read","Update","Delete"]},{"Naam":"MataContactpersonen","AccessType":["Read"]},{"Naam":"MataStudiewijzer","AccessType":["Read"]},{"Naam":"MataProjecten","AccessType":["Read"]},{"Naam":"MataRoosterwijzigingen","AccessType":["Read"]},{"Naam":"MataAftekenen","AccessType":["Update"]},{"Naam":"Oauth","AccessType":["Read","Delete"]},{"Naam":"LeerlingAutorisatie","AccessType":["Read","Update"]},{"Naam":"Persoonsgegevens","AccessType":["Create","Read"]},{"Naam":"Examenresultaten","AccessType":["Read"]},{"Naam":"Terugkommaatregelen","AccessType":["Read"]},{"Naam":"ExamenAfnamemomenten","AccessType":["Read"]}],"Links":null}
```

**Comment by lesander** [comment]
```
{"Naam":"Berichten","AccessType":["None"]}
```
and
```
{"Naam":"MataBerichten","AccessType":["Create","Read","Update","Delete"]}
```
kind of contradict each other right? I'm guessing that MagisterJS doesn't use `Mata` stuff (anymore)?

**Comment by lieuwex** [comment]
@basvdwollenberg Thank you, I will look into it when I'm back home. 

@lesander Yeah that sounds weird, I've no idea whether Mata stuff is even updated since its not used. So maybe the value is always set to allow everything.

But you're right, Magister.js doesn't use anything Mata related.

**Comment by lieuwex** [comment]
@basvdwollenberg Okay I'm really confused, `_profileInfo` shouldn't be `undefined`. 
What does
```JavaScript
new Magister.Magister({
    school: '<schoolname>',
    username: '<username>',
    password: '<password>'
}).ready(function (error) {
    if (error != null) {
		if (error.fouttype === 'OnvoldoendePrivileges') {
			this._ready = true;
		} else {
			console.error('error while logging in', error);
			return;
		}
    }

	console.log('profileInfo ok', this.profileInfo() instanceof Magister.ProfileInfo);
	console.log('id set', this._id != null);
});
```

print?

**Comment by basvdwollenberg** [comment]
It printed
```
profileInfo ok true
id set true
```
so I tried calling `this.profileInfo()` again and somehow it works fine now. Also tried it with `this._setReady()` instead of `this._ready = true`, which results in printing it twice for some reason.
Everything's good now I guess?

**Comment by lieuwex** [comment]
Weird, good that it worked out for you!
I would indeed use `this._ready = true` instead of `this._setReady()` since it recalls all the callbacks set with `.ready`, which is unwanted.

You can use

```Javascript
new Magister.Magister({
    school: '<schoolname>',
    username: '<username>',
    password: '<password>'
}).ready(function (error) {
    if (error != null) {
        if (error.fouttype === 'OnvoldoendePrivileges') {
            this._ready = true;
        } else {
            console.error('error while logging in', error);
            return;
        }
    }

    // [[your code here]]
});
```

and everything should work fine with correct error logging.

**Comment by lieuwex** [comment]
Magister.js v2 will also check the privileges for every function.

**Comment by basvdwollenberg** [comment]
Awesome, thanks again!

**Comment by gruijter** [comment]
@lieuwex When is Magister.js v2 released?

and another question related to this issue: I found out that the 'OnvoldoendePrivileges' error is when you log in as parent, but not as pupil, or vice versa. Now my question: How can I test if the credentials are for a parent or for a pupil? And if the credentials are for a parent, how can I select/retrieve the right information from the pupil (a parent can have multiple pupils associated)

Thx!

**Comment by lieuwex** [comment]
@gruijter 

> When is Magister.js v2 released?

Hard to say, honestly. I couldn't work on it this vacation since Magister is blocked in the summer vacation in my school. I currently can't work on it since I have some troubles with my Magister account.

But I guess it won't be too far off. The hardest part is done.

It will launch as an alpha first though, since I'm not fully sure about some design aspects. You can always help by contributing, though! :wink:

> I found out that the 'OnvoldoendePrivileges' error is when you log in as parent, but not as pupil, or vice versa.

Okay, that's new I guess. I'm also going to add some parent tests in Magister.js v2. Also I'm going to improve parent support in general.

> how can I select/retrieve the right information from the pupil

Assuming it isn't broken since a previous release: http://simplyapps.nl/MagisterJS/docs/classes/Magister.html#method_children

> How can I test if the credentials are for a parent or for a pupil?

In Magister.js 1 there isn't really a clean way to test it, but the `Magister#children` will error when the account isn't a parent account. IIRC I was working on adding a cleaner way to retrieve the account type in Magister.js v2.

**Comment by gruijter** [comment]
Great work! And thx 4 the ultrafast reply.
If I was anything more than a noob I would like to contribute with v2, but unfortunately I started coding just a few months ago and still have to learn a lot (no really, really a lot!)

**Comment by lieuwex** [comment]
Thanks!

Haha, if you see something you think you might be able to do, give it a shot, the best way to learn is by doing. We won't bite. :smile:
