### ISSUE TITLE
[Question] Average grade per school subject? 

### ISSUE THREAD

**Issue by skillzzjesse** [simplyGits/MagisterJS#52]
I can't seem to figure out how to get the average grade per subject calculated by Magister.
(As shown in the green column below)

<img width="40%" alt="screen shot 2016-11-03 at 16 58 40" src="https://cloud.githubusercontent.com/assets/15139826/19973899/e34b0c9a-a1e6-11e6-986a-762f5621be99.png">
  
**The goal is to generate an object like this:**
```js
Grades = {
  subject: AverageGrade,
  ...
}
```
Unfortunately I'm unable to find this type of usability by browsing your documentation. 

Does a way to do this already exist? If so...then how?

**Comment by lieuwex** [comment]
You can use the [`Course#grades`](http://simplyapps.nl/MagisterJS/docs/classes/Course.html#method_grades) function in combination with `Array#find` for this.

With `arr` being the result of `Course#grades`, you could do something like:
```Javascript
var endGrade = arr.find(function (g) {
    return g.type().isEnd() && g.class(). abbreviation === 'SOME_CLASS_ABBREV';
});
```
to get the grade average for a specific class.

**Comment by lieuwex** [comment]
I know grades are a mess in Magister.js currently, with Magister.js v2 it'll be improved.

**Comment by skillzzjesse** [comment]
**Alright, thanks!**


_ps._
I'm currently working on an application that'll give students advice on what to do in KWT (free work) hours based on their grades which is what I need this for.

I had already planned on writing a node package and use it to structure the grades etc. And since I need it fairly quickly.... 

When do you plan on getting v2 out?

**Comment by skillzzjesse** [comment]
## Yes it worked
For any people who are possibly out there trying to do the same...I was able to get the desired result like so: 
```js
Magister = require('magister.js')

new Magister.Magister({
  school: 'xxxx',
  username: 'xxxx',
  password: 'xxxx'
}).ready(function (err) {
  /* Get the current course */
  this.currentCourse(function (err, currentCourse) {
    if (err) {
     // handle error 
    }

    /* Get the grades inside of this course */
    currentCourse.grades(function (err, grades) {
      if (err) {
        // Handle error
      }

      /* Map the grades then log them */
      var returnObj = {};
      grades.forEach(function (grade) {
        // If grade's type is average grade.
        if (grade.type().isEnd()) {
          // Add value to the returnObj (key = class abbreviation) (value = average grade)
          returnObj[grade.class().abbreviation] = grade.grade();
        }
      })
      // Return in the form of a log.
      console.log(returnObj);

    });
  });
})
```
The result listed below:

<img width="385" alt="screen shot 2016-11-03 at 20 55 10" src="https://cloud.githubusercontent.com/assets/15139826/19997808/4035082a-a269-11e6-9c58-cf2508e1baf5.png">

**Note that** the log messages are custom and not included in the code snippet above.
And yes, those are my grades ;)

Enjoy

**Comment by lieuwex** [comment]
> I'm currently working on an application that'll give students advice on what to do in KWT (free work) hours based on their grades which is what I need this for.

Nice, sounds interesting!

> When do you plan on getting v2 out?

I do not have an ETA yet, the code is almost ready to do everything that Magister.js v1 does (files and grades still has to be done), but after that I want to run an alpha first so we can get feedback and make some adjustments to the API and stuff. You can take a look on the [v2 branch](https://github.com/simplyGits/MagisterJS/tree/v2) if you like.

Nice that everything works! :)
