### ISSUE TITLE
[Question] Error handling when school settings Object is not filled in (correctly). 

### ISSUE THREAD

**Issue by skillzzjesse** [simplyGits/MagisterJS#53]
I'm using MagisterJS like so:
```js
new Magister.Magister({

  school: {url: 'xxxx'},
  username: 'xxxx',
  password: 'xxxx'

}).ready(function (err) {

// Catch any errors
if (err) handleError(err);

// Do what needs to be done.....
})
```
The program I'm writing is supposed to be used as a toolkit for structuring data requested from magister outside of the main program. The magister login settings are **not** constants but passed in as an object to the program. Therefore they may contain wrong data or no data at all.
The program I'm writing should be robust and handle all errors properly, giving feedback to the end user.

I've played around a bit with the login settings locally to see what would happen when wrong or no data is passed in.

 This error handling strategy seems to work fine for wrong password/username combinations **however** when either of those is set to `null` it seems the error is no longer handled by the errorhandling of my program but rather just thrown like this:
<img width="1195" alt="screen shot 2016-11-06 at 12 03 42" src="https://cloud.githubusercontent.com/assets/15139826/20037053/379b20c6-a419-11e6-88f8-5dce3a76df99.png">
While normal error handling would look like: 
<img width="1279" alt="screen shot 2016-11-06 at 12 06 03" src="https://cloud.githubusercontent.com/assets/15139826/20037060/693e0f4e-a419-11e6-9b07-2d848b599e8b.png">

**Note** that the 2th image is a custom error message followed by the actual Error Object created by magisterJS and then passed into the `err` parameter of the `callback` given to `.ready()` but the 1th image is just a crash report created by node.js because an error was thrown. 

Furthermore if the value of `url` in the school Object is set to some nonexistent or pure bogus value like so:
```js
school {url: '123'},
username // Etc...
```
 The Error Object that's created by MagisterJS is an empty Object.
<img width="363" alt="screen shot 2016-11-06 at 12 12 33" src="https://cloud.githubusercontent.com/assets/15139826/20037110/545208fa-a41a-11e6-8cb2-55182a5ee066.png">

Setting the url to `null` results ~~in the same not handled error I showed earlier.~~ **Update**: It results in the following unhandled error.
```js
school: {url: null},
username: // Etc...
```
<img width="1280" alt="screen shot 2016-11-06 at 12 31 58" src="https://cloud.githubusercontent.com/assets/15139826/20037301/5240c2ba-a41d-11e6-88a2-8186227be39b.png">

.

When adding a random value to the settings Object like so:
```js
school: {url: 'xxxx'},
random: 'xxxx', // This should not be here at all.
username: 'xxxx',
password: 'xxxx'
```
It results in the same not handled error I showed earlier..
<img width="1195" alt="screen shot 2016-11-06 at 12 03 42" src="https://cloud.githubusercontent.com/assets/15139826/20037053/379b20c6-a419-11e6-88f8-5dce3a76df99.png">

# **Is there a way to catch these errors properly?**
Also, the Empty error when the school url is a nonsense url?
This could be fixed by interpreting empty errors created by magisterJS as wrong url's, but that would mean empty url's are the only case that generate such an error.

**Comment by skillzzjesse** [comment]
**Note** the update regarding setting `url` to `null` like so:
```js
school: {url: null},
// Etc.. 
```

**Comment by skillzzjesse** [comment]
v0.0.0 of the module
https://gist.github.com/skillzzjesse/e39f42dbdf7e0ace7d998032ced732b3

**Comment by lesander** [comment]
1. Make sure your values aren't `null`, but an empty string. 
```js
if (bla===null) {
    bla = '';
}```
2. Profit??

**Comment by skillzzjesse** [comment]
That'll do it for most cases indeed.

**Comment by skillzzjesse** [comment]
#### Actually no, 
passing an empty string as either username or password results in the following.
<img width="1092" alt="screen shot 2016-11-06 at 20 12 41" src="https://cloud.githubusercontent.com/assets/15139826/20040750/6e2fef9c-a45d-11e6-84c1-ff3ea3915c0c.png">
**Note**  how the error is not propperly passed into the error handling logic of my program.

Passing in an empty string as school results in an Empty error as I described earlier.

**Comment by tomsmeding** [comment]
The error is already thrown by the constructor, which gets arguments that is doesn't expect. I think you should just sanity-check your inputs before passing them to the constructor. The `ready` function calls its callback when the object is done *logging in*; with these arguments it can't even *try* to log in, because it misses some arguments.

**Comment by lieuwex** [comment]
Hey thanks for reporting,

I agree with everything that @tomsmeding said.

> The Error Object that's created by MagisterJS is an empty Object.

and

> Setting the url to null results in the same not handled error I showed earlier. Update: It results in the following unhandled error.

Thanks I wil look into that!

> When adding a random value to the settings Object like so:

I can't that error, are you sure you're passing in a school and username&password? It should ignore fields that aren't used.

> Is there a way to catch these errors properly?

Yes, as @tomsmeding said, by using a `try{}catch{}` block around `new Magister`.

> This could be fixed by interpreting empty errors created by magisterJS as wrong url's, but that would mean empty url's are the only case that generate such an error.

Indeed, don't. This is a bug in Magister.js.

> v0.0.0 of the module

Looks nice!

> passing an empty string as either username or password results in the following.

Indeed, if the username or password is empty, `null`, or `undefined` an error is thrown.

---

I would like to point out that constructor errors are given through the promise returned by the login function in Magister.js 2.

**Comment by skillzzjesse** [comment]
@lieuwex 
>I can't that error, are you sure you're passing in a school and username&password? It should ignore fields that aren't used.

Oeps I just tested that again and indeed logging in isn't a problem. That makes things a lot easier 😄 

I'll test out the `try {} catch (e) {}` block around `new Magister` and I think that would cover  any error's but the empty error generated when school is a weird value. 

Thanks for the support!

**Comment by skillzzjesse** [comment]
@lieuwex 
So I tried the `try {} catch {}` block around `new Magister.Magister()` like this: 
```js
function someLoginFunction(settings, callback) {
  
  try {
      // Login to magister using settings as login-data.
      var magisterlogin = new Magister.Magister(settings);
    } catch (err) {
      callback(err); // Early return to callback witht the Error.
    }

    // Return to callback when done logging into magister.
    magisterlogin.ready(function (err) {
      // Invoke callback when logged into magister. (if callback exists)
      if (callback) callback(err, this);
    });

}
```

The error isn't randomly thrown anymore but handled by the error handling inside the callback. (as expected) **However** the error seems to be empty.
<img width="358" alt="screen shot 2016-11-07 at 21 21 01" src="https://cloud.githubusercontent.com/assets/15139826/20074343/2438ccfa-a530-11e6-93d1-c811e4880b99.png">


**Am I doing this right?** The error that was randomly thrown and not handled properly didn't seem to be empty... The fact I'm getting an empty error seems weird...
