### ISSUE TITLE
[question] Empty error's when loggin into magister after the update? (v1.22.1)

### ISSUE THREAD

**Issue by skillzzjesse** [simplyGits/MagisterJS#55]
**Please note that** this issue has already been mentioned in other issues (#53 & #54). However it is still weird for me. 

## Error's caught by the errorhandling is empty even after the update?(https://github.com/simplyGits/MagisterJS/commit/78c863a4ec59b35ae3fcaa5945d96052200f760b)
* **magister.js version: `1.22.1`**

## My code:
```js
function someLoginFunction(settings, callback) {
  
  try {
      // Login to magister using settings as login-data.
      var magisterlogin = new Magister.Magister(settings);
    } catch (err) {
      callback(err); // Early return to callback witht the Error.
    }

    // Return to callback when done logging into magister.
    magisterlogin.ready(function (err) {
      // Invoke callback when logged into magister. (if callback exists)
      if (callback) callback(err, this);
    });

}
```

For this particular test case I've set the login settings object like so:
```js
{
  school: {url: 'x'},
  username: my_username,
  password: my_password
}
```
## The result: 
<img width="361" alt="screen shot 2016-11-08 at 19 03 29" src="https://cloud.githubusercontent.com/assets/15139826/20110807/180e2af4-a5e6-11e6-851e-57f8a27574d5.png">

--- 

For the next test case I've configured the login settings object like so:
```js
{
  school: {url: my_magister_url},
  username: my_username,
  password: ''
}
```
## The result: 
<img width="353" alt="screen shot 2016-11-08 at 19 05 44" src="https://cloud.githubusercontent.com/assets/15139826/20110879/703b0d8c-a5e6-11e6-9cf5-c7ceeabaa024.png">

---

Since the update to v1.22.1  and commit https://github.com/simplyGits/MagisterJS/commit/78c863a4ec59b35ae3fcaa5945d96052200f760b were focused on fixing this (for the url case, the password case should already be working) I feel like I'm doing something wrong on my part. 

**How should this be done?**

---
***ps:*** *Sorry for the double issue, I had already mentioned this in #53 however I felt like a separate issue would be in order since the update (1.22.1).*

**Comment by lieuwex** [comment]
Are you perhaps calling `JSON.stringify` before printing the error? I recommend just calling `toString()` on it. Since the error that is thrown by the constructor is an `Error`, not a plain object. (this is normalized in m.js v2)

**Comment by skillzzjesse** [comment]
The error handling of my program is simply a `console.log()` of the `err` with some error prefix. So I'm not calling anything on the error object.

**Comment by skillzzjesse** [comment]
I'll test if calling `toString()` will resolve the issue.   
**Note** how errors called by `.ready()` are properly caught by the program.

Does magister.js do something with these error Objects? How are they different?

**Comment by skillzzjesse** [comment]
> The error handling of my program is simply a console.log() of the err with some error prefix. So I'm not calling anything on the error object.

So I was going to post my entire error handling function etc. and checked the code for any stupid mistakes I made during copying when I noted that **I am calling `JSON.stringify(error)`**. 

Stupid mistake of me not to check my code properly. (I copied the error handling function from another project without looking at it.) 

I'll check if updating `JSON.stringify(error)` to sinply calling `.toString()` on it will work ASAP. And then consider this issue closed. 😄 

Thanks for the help, as always!

**Comment by skillzzjesse** [comment]
YUS, it works!

**Comment by lieuwex** [comment]
> Does magister.js do something with these error Objects? How are they different?

Currently, errors during login are just plain objects, with a `toString` and `message` as properties. An error during the creation of the `Magister` object is made using the `Error` object, though, which can't be serialised.

In Magister.js v2 login errors will be `MagisterError` error instances, which extend the `Error` class, so there isn't a practical difference handling login errors and errors creating in the constructor. Authentication errors will be an instance of the `AuthError` class, which again is also a subclass of the `Error` class, but easy to check against (`error instanceof AuthError`).

So I know errors aren't really clear now, but they will be in v2. :)

**Comment by skillzzjesse** [comment]
## I'm glad to hear v2 will have so many improvements! 

*(btw: Will v2 make [my package (magister-tools)](https://github.com/skillzzjesse/magister-tools) unnecessary? Since its  only used to filter the endGrades from a list of grades right now.)*

**Comment by lieuwex** [comment]
Nope! It will maybe even make your library more useful, since I'm trying to slim down m.js with v2. So many 'helper' functions like `getCurrentCourse` will be removed. Grades will not really be that much different from how they're currently, I'm just planning on making the API more clear. But the idea will be the same.

**Comment by skillzzjesse** [comment]
Cool! 
If you think of any features you might useful please take a look at the "suggestions"  section in the Readme of my repository.
