### ISSUE TITLE
[question] Even more error's? (double error)

### ISSUE THREAD

**Issue by skillzzjesse** [simplyGits/MagisterJS#56]
(*Yeah, it's me again...*)

# Double error?
When trying to login to magister using magisterJS you sometimes get an error like this:
```js
{
  "code": "ETIMEDOUT",
  "errno": "ETIMEDOUT",
  "syscall": "connect",
  "address": "188.65.196.39",
  "port": 443
}
```
*I think this is magister limiting the amount of request you can send but I'm not entirely sure...*

Anyways, this error is obviously properly caught by the callback of `Magister.ready()` and can be dealt with no problemo **however** magisterJS also throws its own error: 
```js
throw new Error("Not done with logging in or errored during logging in! (did you use Magister.ready(callback) to be sure that logging in is done?)");
```

### I'm catching the error's like so:
```js
function someLoginFunction(settings, callback) {
  try {
    var magisterlogin = new Magister.Magister(settings);
  } catch (err) {
    callback(err) // Early return to callback with the error.
  }

  magisterlogin.ready(function (err) {
    callback(err)
  });
}
```

This new (double) error is not caught by this error handling technique, this is expected since the error is (probably) thrown by the constructor **after** the `Magister.ready()` callback and therefore **not** caught by the 1st `try { } catch { }` block. (or the callback of `Magister.ready()`)

I'm writing a test server that logs into magister using login data provided in the request and my (test) server is able to nicely send a response containing the first error described above. However the second error causes my server to crash since this error is thrown and not handled.

I've been wrecking my brain over this and the only possible solution I can think of is wrapping the entire `someLoginFunction` inside a `try { } catch { } ` block when called. (including all of its callbacks etc.) 

Is there some other way to properly catch and handle this error?

**Comment by skillzzjesse** [comment]
# Update
I've now tried the extra `try {} catch {}` block around my login function but even this doesn't seem to fix the problem. The server (run on localhost) still crashes by the non handled error: 
```js
throw new Error("Not done with logging in or errored during logging in! (did you use Magister.ready(callback) to be sure that logging in is done?)");
```

### The "login" function looks like this:
It uses [magister-tools](https://github.com/skillzzjesse/magister-tools) to simplyfy the amount of code I need to write in my file. 

```js
function getEndGrades (settings, callback, doFirst) {
  /* Login to magister using settings as login. */
  m_tools.magisterLogin(settings, function (err, magisterlogin) {
    if (err) {
      callback(err); // Return to callback with this error.
    }

    /* Fetch the current course for the logged in user. */
    m_tools.fetchCurrentCourse(magisterlogin, function (err, course) {
      if (err) {
        callback(err); // Return to callback with this error.
      }

      /* Fetch the grades for the current course of the logged in user. */
      m_tools.fetchGrades(course, function (err, grades) {
        if (err) {
          callback(err); // Return to callback with this error.
        }
        /* Get the average grades from this list of grades. */
        var endGrades = m_tools.getEndGrades(grades);

        /* Return to callback with the end grades (Average grades.) */
        callback(null, endGrades);
      });
    })

  }, doFirst);
}
```

### This is what's happening inside my server logic: 
The `try {} catch {}` block. 
Note how `tools.log` is basically a function that formats `console.log` for me making it easier to read through my log messages.
```js
try {
     /* Get the end grades from magister using the request's body as login. */
     getEndGrades(req.body, function (err, endGrades) {
       if (err) {
         tools.log("error", "Problem while getting end grades from Magister", err)
         res.status(500);
         res.send(err);
         res.end();
       }

       if (!err) {
         /* Respond with the end grades: */
         res.status(200); // OK
         res.send(endGrades);
         /* Log our success */
         tools.log("info", "Responded with the grades.\n")
       }

     }, function () {
       /* doFirst function */
       tools.log("info", "Getting end grades from Magister.")
     })
   } catch (err) {
     /* Catch aditional error's that might happen. */
     tools.log("error", "catch: problem getting end grades from Magister.", err)
   }
```

# The response
The response to the request send to this (test) server looks like this:
```js
{
  "code": "ETIMEDOUT",
  "errno": "ETIMEDOUT",
  "syscall": "connect",
  "address": "188.65.196.39",
  "port": 443
}
```
This is what the console looks like:
<img width="1280" alt="screen shot 2016-11-13 at 16 03 45" src="https://cloud.githubusercontent.com/assets/15139826/20246628/fdf4ac00-a9ba-11e6-85e9-faf2a4b3d1d7.png">

# Conclusion
As you can see the error is **not** caught by this technique either however it is beyond me why the error escapes the `try {} catch {}` block on the top level of the code.

**Comment by tomsmeding** [comment]
Hi there!

I see a recurring pattern in your code that might (or might not) be the source of most of your problems. I thought someone had said this already, but apparently not. Please see the following code:

```js
functionThatCanError(function(err,res){
    if(err){
        console.log("Something bad happened!");
        console.log(err);
    }
    doSomethingWith(res);
});
```

See the problem? What happens when `err` isn't `null`?

You log something about the error, and then happily continue to `doSomethingWith(res)` as if everything was all right.

Your code under the heading "The login function looks like this" does this three times, each time with a comment `// Return to callback with this error`, as if calling the callback returns from the function, which it doesn't. It just calls the callback, and then continues with the rest of the code below that line.

If you do this, and an error occurred, then `res` isn't going to contain something useful when you `doSomethingWith(res)`. In fact, it might throw an error that you don't expect (hint). Also, a callback might be called multiple times (hint).

I see that in your "server logic", you _almost_ made the same mistake: you first check for an error with `if(err){...}` (without returning from the function if that happens), and then, only if `!err`, run the rest of the code. This style of coding works, but the next time I'd have to write a callback with an error argument, I'd instantly forget to add the `if(!err)` around the rest of the function body. (And this is exactly what you're doing in your other code.)

You should go over your code and in callbacks that have to deal with an error argument, fix the callback to `return` from the function after the error is dealt with. For example, to fix my code above:

```js
functionThatCanError(function(err,res){
    if(err){
        console.log("Something bad happened!");
        console.log(err);
        return; // Please add this.
    }
    doSomethingWith(res);
});
```

Hope this helps.

**Comment by skillzzjesse** [comment]
OMG I totally looked over that, 
I should indeed `return` right away that makes a lot of sense 😂 

Thanks a lot for the eye opener!
Sometimes learning too many new things in a short amount of time can cause you to forget important details. 

Again, many thanks!

**Comment by lieuwex** [comment]
Thanks @tomsmeding for your clear and detailed explanation!

@skillzzjesse 
I want to add to this:

> Is there some other way to properly catch and handle this error?

No, this error is not designed to be caught, but more to indicate a structural error of the code. Just like in this case (forgotten `return`s)

**Comment by skillzzjesse** [comment]
Hahah I get it now, stupid mistake.

**Comment by lesander** [comment]
_offtopic_
@lieuwex Will MagisterJS v2 work with Promises or bluebird?

**Comment by lieuwex** [comment]
@lesander Native es6 promises to keep things simple and portable. Although bluebird has some compelling features, I don't think they're worth the price of depending on a lib. I'm trying to keep m.js2 light on the dependencies.

**Comment by lesander** [comment]
Awesome. :+1: for ES6 support :) I'm not a big fan of Bluebird either, but it offers support for wrapping non-promise modules into to Promises.
