### ISSUE TITLE
The license...

### ISSUE THREAD

**Issue by elisaado** [simplyGits/MagisterJS#58]
Hey, do you guys think a LGPL license is the best option for this project? If I was you I'd rather use the *MIT* license...

This means that every project that uses your API has to make it's source code available, this isn't always what developers want...
```
(b) If you do distribute YOUR APPLICATION, and you used something GPL as part of your application (even if only linking at run-time to a library) - and even if you do not charge money - and even if you do not change that GPL s/w in any way - then you MUST make the source of YOUR APPLICATION available.
(From http://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application)
```

However, with the MIT license, this isn't needed;
```
you CAN:
re-use the code freely for your own use,
re-use the code freely for non-commercial AND commercial re-distribution, whether in source or binary form.
you CANNOT:
claim authorship of the software,
thus you cannot attack the original author for using or publishing his original version.
(From http://softwareengineering.stackexchange.com/questions/103273/can-i-use-mit-licence-plugins-in-my-commercial-web-site)
```

I hope you guys consider switching to another license that doesn't need developers to make their source code available :+1:

Thanks in advance!

Eli Saado

**Comment by lieuwex** [comment]
I think you're confusing LGPL with GPL, if a project uses a library using a LGPL license, the author doesn't need to publish the source code. Although, if changes are made to the library the author needs to publish the changes. (so only of the library)

I chose for LGPL instead of MIT because I want Magister.js to stay freely available and to create a nice developer community, so that if a commercial player would use Magister.js and be able to make some good changes to it, it's required to publish them for the community's good.

**Comment by bwired-nl** [comment]
Yeye agree Lieuwe 😊

**Comment by elisaado** [comment]
```I think you're confusing LGPL with GPL```
Probably yeah


```if a project uses a library using a LGPL license, the author doesn't need to publish the source code. ```
Wow! Good to know :smile: 


```Although, if changes are made to the library the author needs to publish the changes. (so only of the library)```
I'm not planning to make changes to the library so that's good for me :laughing: 


```I chose for LGPL instead of MIT because I want Magister.js to stay freely available and to create a nice developer community, so that if a commercial player would use Magister.js and be able to make some good changes to it, it's required to publish them for the community's good.```
Aaahhh Yeah


```Hope that cleared it up for you :)```
Yes you did thanks!

**Comment by lieuwex** [comment]
:)
