### ISSUE TITLE
student.fullName does not include namePrefix

### ISSUE THREAD

**Issue by gruijter** [simplyGits/MagisterJS#59]
In ProfileInfo class I expect the student.fullName to be firstName+namePrefix+lastName. The namePrefix is however not included.

**Comment by lieuwex** [comment]
Thanks, that's indeed better.

**Comment by gruijter** [comment]
Great, Thx for the fast response and fix!

**Comment by gruijter** [comment]
Now that I have your attention ( :) ) Maybe you can help this noob with the following:
I want to display the student photo in a html frontend. In the backend (node server) I can retrieve the photo url ( Magister.profileInfo().profilePicture() ), but when I use this in the frontend I receive a 403 Forbidden.

How can I retreive the image from the school's url that requires authentication?

Hope you are willing&able to help.

**Comment by gruijter** [comment]
By the way... I updated magister.js with npm update. But I still do not have namePrefix included in the fullName. Am I doing something wrong?

**Comment by lieuwex** [comment]
> By the way... I updated magister.js with npm update. But I still do not have namePrefix included in the fullName. Am I doing something wrong?

I still have to publish a new version, will do in a bit, I will tell you when it's published. Then `npm update` should work, sorry for the confusion.

**Comment by gruijter** [comment]
Cool! Thx 4 taking the time to help me out. Keep up the good work 👍

**Comment by lieuwex** [comment]
No problem, thank you :)

**Comment by lieuwex** [comment]
@gruijter New version (`1.23.0`) has been published!

**Comment by gruijter** [comment]
Thx!, But unfortunately the fullName now has 'null' between firstName and lastName if the namePrefix is null..... :(

**Comment by lieuwex** [comment]
Omg you're right I'm so stupid 😂 will fix in a moment.

**Comment by lieuwex** [comment]
@gruijter 1.23.1 has been published with a fix by @zwebfek 😄

**Comment by gruijter** [comment]
Happy 🤗👍
