### ISSUE TITLE
'Invalid API key'

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#68]
Fuck, shit, help. The end is upon us.

**Comment by tomsmeding** [comment]
Explain

**Comment by idiidk** [comment]
I got this same error but fixed it by including the X-API-Client-ID header in the requests sent to the server. I did this by making a small edit to the cookie inserter. The API key itself i extracted by logging in to Magister form the browser and looking at the requests. For my school its 12D8. I dont know if this is the right solution but it works for me!

**Comment by lieuwex** [comment]
@idiidk Thanks! That seems to be it, working on a fix!

As a bonus, is the Magister app broken by this, seems unlikely, but I tried to use the app and it didn't work at all.

**Comment by idiidk** [comment]
@lieuwex Seems to be loading fine for me, maybe just the servers being slow?

**Comment by lieuwex** [comment]
Quick patch released, sorry for the horrible late reaction and stuff: https://github.com/simplyGits/MagisterJS/releases/tag/1.23.3

I'm currently failing with making a correct patch for whatever reason (it should be simple), but this _seems_ to work. All schools seem to have the same apiKey.

@idiidk I have no idea, and I don't really care about the official app either :P

**Comment by lieuwex** [comment]
![](https://media.giphy.com/media/z9AUvhAEiXOqA/giphy.gif)

**Comment by lesander** [comment]
Can confirm, all magister schools seem to have the same `X-API-Client-ID:12D8` header set for each API request.

Settings are hard-coded in `https://school.magister.net/magister/index.html` around lines 70 - 90.
```html
<script type="text/javascript">
    var globalSettings = {
        apiHost: 'https://school1.magister.net/',
        applicationLoUrl: '/magister',
        applicationOpUrl: '/op',
        accountUrl: '',
        deviceType: 'desktop',
        timeout: 1200,
        isMobileApp:  false ,
        browserVersion: '',
        offlineSupport:  false ,
        showOnedriveConnectionWarning: true ,
        clientVersion: '2.9.62108.0',
        apiKeyHeader: 'API-Client-ID',
        apiKey: '12D8',
        emailVerificatie: true ,
        kennisnetLogin: true 
    };
</script>
```
```html
<script type="text/javascript">
    var globalSettings = {
        apiHost: 'https://school2.magister.net/',
        applicationLoUrl: '/magister',
        applicationOpUrl: '/op',
        accountUrl: '',
        deviceType: 'desktop',
        timeout: 1200,
        isMobileApp:  false ,
        browserVersion: '',
        offlineSupport:  false ,
        showOnedriveConnectionWarning: true ,
        clientVersion: '2.11.8.2',
        apiKeyHeader: 'API-Client-ID',
        apiKey: '12D8',
        emailVerificatie: true ,
        kennisnetLogin: true 
    };
</script>
```

**Comment by bwired-nl** [comment]
can somebody help me
i have now this
getGrades ( {school: {url: 'https://dspierson.magister.net'},username: 'xxxxx',	password: 'xxxxx'}, function ( err, grades) {
		//console.log('result ROWS : ' + util.inspect(grades));
								
		for (var index in grades) {

etc.
i get this error
Cannot read property 'length' of null
how can add the above api etc

thanks very

**Comment by idiidk** [comment]
@bwired-nl 
You dont call the API like that, instead you have to first create a Magister instance: 
```
new Magister.Magister({
    school: 'xxxx',
    username: 'xxxx',
    password: 'xxxx'
}).ready(function (error) {
    currentCourse(function (err, result) {
        if (err) {
            console.log(err);
        } else {
            this.grades(function (err, result) {
                //CODE HERE FROM RESULT
            });
        }
    });
});
```

Here is the documentation of the API for further reading: [[API|http://simplyapps.nl/MagisterJS/docs/index.html]]

**Comment by bwired-nl** [comment]
it always worked till some days ago, i will check
thanks!!

**Comment by idiidk** [comment]
Aantal kids op school xD

**Comment by bwired-nl** [comment]
yes i have 8 kids LOL

**Comment by elisaado** [comment]
LOL, seems like they wanted to "protect" their API by adding api keys, well, super smart to have it be `12D8` for every school.

**Comment by elisaado** [comment]
How to find your school's API key: (in case they change it to not be the same for every school)
![image](https://cloud.githubusercontent.com/assets/14182500/26064412/293a8054-3991-11e7-803e-e57a36388eb9.png)

**Comment by lieuwex** [comment]
I've no idea if it's really a protection scheme or if it's something for analytics, let's not speculate :p

If they will ever use different api keys per school we should be able to easily support that in the future.

**Comment by elisaado** [comment]
Yeah you're right

We(?) could maybe have a database built in which it checks when making requests
Like

|school|key|
|_______|__|
|a|a|
|a|a|

But I'm not sure whether they want to do that to us(?) :p.

**Comment by Sj3rd** [comment]
The issue still appears, and it seems to be that every school has a different api key: 
![image](https://user-images.githubusercontent.com/33723199/47007582-dd8a4400-d138-11e8-9a26-7930728188d2.png)

**Comment by lieuwex** [comment]
@Sj3rd Hmm that sucks, I guess we'll have to extract it from the globalSettings payload in the HTML then. @idiidk What do you think?

**Comment by Sj3rd** [comment]
Well, I'm pretty new to JS api's, so I'm not sure how to start the service😞. Not tested the Magister.js API yet.

**Comment by Sj3rd** [comment]
@idiidk fixed it. For some reason after I did a request with the custom API-Client-ID of my school, I was able to make requests with the unchanged api. Now works flawless.

Gonna upgrade the magister-api from idiidk to the alpha version of this JS api :)

@lieuwex The API isnt clientside runnable right?

**Comment by lieuwex** [comment]
@Sj3rd If you mean runnable in a browser, no. v1 had _some way_ to work around that using a serverside proxy. But it's just ugly and really unnecessary. You should only run Magister.js from a node instance, and set up an API for yourself if needed. Browsers can't directly connect to Magister's servers because of their same-origin policy.

**Comment by Sj3rd** [comment]
@lieuwex ah ok. Because the v1 also included the browserversion, I was hoping I could call magister directly from client side js. 

Since Google Cloud Functions is blocked by magister, I cant see any other way to host a node server apart from hosting it some kind of homeserver here in the Netherlands. Maybe we should have one up to date server where we can make calls to.
