### ISSUE TITLE
profileInfo().profilePicture not working anymore

### ISSUE THREAD

**Issue by gruijter** [simplyGits/MagisterJS#70]
This used to work, but not anymore (invalid API key?). I'm using v1.24.1.

      request.get({
        url: this.profileInfo().profilePicture(128, 128, false),
        encoding: null,
        headers: {
          cookie: this.http._cookie
        },
      }).pipe(fs.createWriteStream('./userdata/'+this.magisterSchool.name+'_'+this.profileInfo().id()+'.jpg'));

**Comment by lieuwex** [comment]
Try adding
 'X-API-Client-ID': '12D8'
to the headers

**Comment by gruijter** [comment]
yep, that does the trick. Can you fix it, or do I need to keep this in the header?

**Comment by lesander** [comment]
@gruijter See issue https://github.com/simplyGits/MagisterJS/issues/68#ref-commit-cbc8300. The `X-API-Client-ID` header with value `12D8` is required for all requests to the Magister API.

**Comment by lieuwex** [comment]
@gruijter exactly what @lesander says, you need to keep this in the header. Magisterjs v2 will download the picture instead, so you won't have to do a request and provide the headers. The lib will do it for you instead.
