### ISSUE TITLE
`profileInfo#isChild` provides inconsistent results

### ISSUE THREAD

**Issue by gruijter** [simplyGits/MagisterJS#71]
Hi @lieuwex,

You helped me a while ago with caching the Magister object (see below). My question now is this: My code now only works when a student credentials' are used. When the parents' credentials are used things get very complicated. Is there a way for the cache to return the child object only when a parent logs in? I am really a noob on the subject of handling complex objects and functions like Magister. I tried to use .bind but I just do no grasp how this works. Hope you can bring a simple solution. Thx!

```javascript
let getMagister = (function () {
	let magisterCache = {};
	return function (credentials) {
		let id = credentials.school + '_' + credentials.username+ '_' + credentials.password;
		let magister = magisterCache[id];
		if (magister === undefined) {
			magister = new Magister.Magister(credentials);
			magisterCache[id] = magister;
		}
		return magister;
	};
})();

getMagister(credentials).ready(function (error) {
```

**Comment by lieuwex** [comment]
Do you want to support multiple children per parent account?

**Comment by gruijter** [comment]
yes, but I would already be happy if I can understand how a single child can be supported!

**Comment by gruijter** [comment]
@lieuwex any help you can provide for this? Much appreciated!

**Comment by gruijter** [comment]
@lieuwex bump

**Comment by lieuwex** [comment]
Sorry I was busy (I'm in my exam year), this _should_ work, didn't test:

```
const getMagister = (function () {
	const magisterCache = {};

	return function (credentials, callback) {
		const id = credentials.school + '_' + credentials.username;

		const magisters = magisterCache[id];
		if (magisters !== undefined) {
			setImmediate(function () {
				callback(null, magisters);
			});
			return;
		}

		new Magister.Magister(credentials).ready(function (err) {
			if (err != null) {
				callback(err, []);
				return;
			}

			const provide = function (err, res = []) {
				if (err == null) {
					magisterCache[id] = res;
				}
				callback(err, res);
			};

			if (this.profileInfo().isChild()) {
				provide(null, [ this ])
			} else {
				this.children(provide);
			}
		});
	};
})();
```

You can use it with the same credentials as before, but instead of this function returning a magister instance, you should provide it a callback as second argument which gets an error and an array of magister instances. (This will be an array of length 1 when the provided credentials were of a child, otherwise it will contain all the children)

**Comment by gruijter** [comment]
@lieuwex Super that you are taking the time to do this during your exam year! Hope you do very well 👍 

I tried the code, but get an error on this part:
const provide = function (err, res = []) { ....

Is that a valid statement for node.js v4.8.2 ?

**Comment by lieuwex** [comment]
try changing
```javascript
			const provide = function (err, res = []) {
				if (err == null) {
					magisterCache[id] = res;
				}
				callback(err, res);
			};
```
into
```javascript
			const provide = function (err, res) {
                                res = res || [];
				if (err == null) {
					magisterCache[id] = res;
				}
				callback(err, res);
			};
```

**Comment by gruijter** [comment]
Yes, I think this might be working. Will try more another day :)

**Comment by gruijter** [comment]
No, the code is only working for parents now. For children I always get "OnvoldoendePrivileges". I think the problem is in this bit:
```			if (this.profileInfo().isChild()) {
				provide(null, [ this ])
			} else {
				this.children(provide);
			`}
```
For the school I'm testing with the this.profileInfo().isChild() is always false, for both parent and child. Furthermore, shouldnt the else part be similar to the if part? so, something like this (which does not work by the way):
```			if (this.profileInfo().isChild()) {
				provide(null, [ this ])
			} else {
				provide(null, [ this.children ])
			`}
```

**Comment by lieuwex** [comment]
What's the full traceroute? But no, `this.children` is a function, it has to be executed first.

**Comment by gruijter** [comment]
I found that the .isChild() function seems to give random results. It is almost always 'false' for both parent and child. But sometimes it is 'true' for the parent. Note: Each time I'm using the same parent and the same child login!

**Comment by gruijter** [comment]
When using this it works (but I think that using the birthdate is working for my son more of a coincidence)

```
			if (this.profileInfo().birthDate() !== undefined) {
				provide(null, [this]);
			} else {
				this.children(provide);
			}
```

**Comment by lieuwex** [comment]
Hmm I will take a look, thanks

**Comment by gruijter** [comment]
Any news on this yet? 😎

**Comment by gruijter** [comment]
Bump. Any news?

**Comment by lieuwex** [comment]
Not really, I can't login anymore and am not really active anymore since I'm finished with high school and busy with other stuff already. :P

Sorry for the _super_ late reply, my bad. :( See #76 if you're interested in continuing Magister.js
