### ISSUE TITLE
Always error 'An error has occurred' when trying to login

### ISSUE THREAD

**Issue by gruijter** [simplyGits/MagisterJS#72]
I don't know when it started, but I now always get 'An error has occurred' when trying to login using valid credentials. The Magister website still works though with the same credentials....

**Comment by lieuwex** [comment]
Are you sure you're on the latest version? (1.24.1)
It seems to work fine for me here

**Comment by gruijter** [comment]
Yes, and I have also tried on the webbased tryout http://simplyapps.nl/MagisterJS/tryout/index.html

I tried:
* two different students who are on different schools
* with the student login and the parent login
* from my own app using v 1.24.1 module
* from different devices using the tryout webpage
* from different IP addresses

Loging in on the magister website itself does work with the same credentials....

This situation has lasted for about a week now, and I don't know what to do next :(

**Comment by lieuwex** [comment]
Weird, What's the school URL?

**Comment by lieuwex** [comment]
Got the school URLs per email privately. Problem seems to be upstream.
