### ISSUE TITLE
Error with connection

### ISSUE THREAD

**Issue by wipeautcrafter** [simplyGits/MagisterJS#78]
When I try to connect to the API, it throws the following error:
```
error! { fouttype: 'OnvoldoendePrivileges',
  omschrijving: null,
  toString: [Function] }
```
Is it because the Magister API is constantly updating?
I am using the following code:

```javascript
var Magister = require('magister.js');
var conn = new Magister.Magister({school: '***', username: '***', password: '***'});
conn.ready((err) => {
	if(err) console.log("error!", err);
	console.log("ready!");
});
```

**Comment by lieuwex** [comment]
It is probably indeed because Magister updated the API, I'm not in highschool anymore so I don't have the time or the will to keep maintaining Magister.JS. See #73 and #76.

**Comment by Wqrld** [comment]
magister.js still works for me ( appart from that my account is now blocked because of it) so i guess either your school uses a special system or you messed up your username | pw | schoolname
