### ISSUE TITLE
When logging in with token, no profileinfo is given back

### ISSUE THREAD

**Issue by netlob** [simplyGits/MagisterJS#90]
When you login with a Bearer token, profileInfo is null.

code used to login with bearertoken:
```js
getSchools(<schoolname>)
	.then((schools) => schools[0])
	.then((school) => magister({
		school,
		token: <bearer-token>
	}))
	.then((m) => {
		console.dir(m);
	}, (err) => {
		console.error('something went wrong:', err);
	});
```

Also Im unable to request any other data when logging in with the token.

**Comment by Sj3rd** [comment]
update: it's not only that the profileInfo is null, you're not even logged in at all. The only thing you get back from logging in with a token, is infomation you gave when you called the login (school and the token).

Maybe @idiidk can add a variable like savedauth where you can reauthenticate with (just like in his own api :) )

**Comment by lieuwex** [comment]
Seems that https://github.com/simplyGits/MagisterJS/commit/7007b8cbc60b5da171b5f7ca08bce36f764ad8d7#diff-6b8f6a1f5e260a6e0da28357458b75deR386 was a bit too aggressive of a change (cc: @idiidk) (now the whole accountdata fetch is skipped)

**Comment by idiidk** [comment]
Ooh shiii... I probably removed something important, looking into it now

**Comment by Sj3rd** [comment]
How can I update to this fixed version? Its not published to npm yet

**Comment by lieuwex** [comment]
@Sj3rd I will publish it, otherwise you can also install magisterjs to a project using `npm install simplyGits/MagisterJS`, instead of `npm install magister.js`. Then it uses the git version instead of the npm version.
