### ISSUE TITLE
Crash in Http#_request when response is a string

### ISSUE THREAD

**Issue by lieuwex** [simplyGits/MagisterJS#94]
As reported by @gruijter in https://github.com/simplyGits/MagisterJS/pull/93#issuecomment-436697084.

**Comment by gruijter** [comment]
Is this maybe solved in alpha4?

Login with token is now working.

**Comment by lieuwex** [comment]
Oh yes, I forgot to ask. I guess it should be working now since we've overhauled the _request method. Thanks.

We can reopen this if the issue persists.
