### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by ImranDoet** [simplyGits/MagisterJS#96]
The docs are unclear. For example:
http://simplygits.github.io/MagisterJS/GradePeriod.html
The parameters are magister, which is clear and raw, what in the world's name does raw mean? This can be seen everywhere in the docs. I cant do anything now because I don't know what raw means.

**Comment by lieuwex** [comment]
I've uploaded improved docs, hopefully it's now more clear what is and what isn't public and stuff. :)

**Comment by ImranDoet** [comment]
Thanks :+1:
