### ISSUE TITLE
Please add latest grades

### ISSUE THREAD

**Issue by Sj3rd** [simplyGits/MagisterJS#99]
Please add a latestGrades fcuntion, which gives the latest grades. Its a different request than the normal Grades() function.

To get grades we call: ${this._magister._personUrl}/aanmeldingen/${this.id}/cijfers

To get the latest grades the request would be: ${this._magister._personUrl}/aanmeldingen/${this.id}/cijfers/laatste?top=50&skip=0

**Comment by Argetan** [comment]
Hey there! I, in theory, implemented the function. However the URL`${this._magister._personUrl}/aanmeldingen/${this.id}/cijfers/laatste?top=50&skip=0` appears to be invalid. Any idea where I could find the correct URL?

https://github.com/Argetan/MagisterJS/blob/a77ea25745e9ffc5bc8c1cf12bd8d0d2e44ebb14/src/course.js#L92-L118

**Comment by Argetan** [comment]
I figured it out.
